import Foundation
import SwiftData

/// An AI personality that guides creative suggestions and interactions.
///
/// Ghost personalities define the tone, style, and behavior of the AI assistant
/// during creative sessions. They can be built-in or user-created, and optionally
/// sold on the marketplace.
@Model
final class GhostPersonality: @unchecked Sendable {

    /// Unique identifier for this personality.
    @Attribute(.unique) var id: UUID

    /// Display name of the personality.
    var name: String

    /// A short description of the personality's creative style.
    var personalityDescription: String

    /// The system prompt sent to the AI backend when this personality is active.
    var systemPrompt: String

    /// The user who created this personality, or `nil` for built-in personalities.
    var creatorId: UUID?

    /// Identifier for the haptic feedback pattern associated with this personality.
    var hapticPattern: String

    /// Identifier for the text-to-speech voice used by this personality.
    var voiceId: String

    /// Descriptive trait keywords for this personality.
    var traits: [String]

    /// A label describing the overall response style (e.g. "concise", "verbose").
    var responseStyle: String

    /// How many times this personality has been used across all sessions.
    var usageCount: Int

    /// Average user rating on a 0–5 scale.
    var rating: Double

    /// Price to purchase this personality, or `nil` if free.
    var purchasePrice: Double?

    /// Total revenue generated by this personality.
    var revenue: Double

    /// Total number of downloads.
    var downloads: Int

    /// Whether this personality is published to the marketplace.
    var isPublished: Bool

    /// Optional custom training data provided by the creator.
    var customTrainingData: [String]?

    /// Creates a new ghost personality.
    ///
    /// - Parameters:
    ///   - id: Unique identifier. Defaults to a new UUID.
    ///   - name: Display name.
    ///   - description: Short description of the personality.
    ///   - systemPrompt: The AI system prompt.
    ///   - creatorId: Creator's user ID, or `nil` for built-in.
    ///   - hapticPattern: Haptic pattern identifier.
    ///   - voiceId: Voice identifier.
    ///   - traits: Trait keywords.
    ///   - responseStyle: Response style label.
    ///   - usageCount: Initial usage count. Defaults to `0`.
    ///   - rating: Initial rating. Defaults to `0`.
    ///   - purchasePrice: Price, or `nil` if free.
    ///   - revenue: Total revenue. Defaults to `0`.
    ///   - downloads: Total downloads. Defaults to `0`.
    ///   - isPublished: Published state. Defaults to `false`.
    ///   - customTrainingData: Optional training data.
    init(
        id: UUID = UUID(),
        name: String,
        description: String,
        systemPrompt: String,
        creatorId: UUID? = nil,
        hapticPattern: String = "default",
        voiceId: String = "default",
        traits: [String] = [],
        responseStyle: String = "balanced",
        usageCount: Int = 0,
        rating: Double = 0,
        purchasePrice: Double? = nil,
        revenue: Double = 0,
        downloads: Int = 0,
        isPublished: Bool = false,
        customTrainingData: [String]? = nil
    ) {
        self.id = id
        self.name = name
        self.personalityDescription = description
        self.systemPrompt = systemPrompt
        self.creatorId = creatorId
        self.hapticPattern = hapticPattern
        self.voiceId = voiceId
        self.traits = traits
        self.responseStyle = responseStyle
        self.usageCount = usageCount
        self.rating = rating
        self.purchasePrice = purchasePrice
        self.revenue = revenue
        self.downloads = downloads
        self.isPublished = isPublished
        self.customTrainingData = customTrainingData
    }
}

// MARK: - Built-in Personality Factories

extension GhostPersonality {

    /// The Muse — an encouraging, free-flowing creative companion.
    static func theMuse() -> GhostPersonality {
        GhostPersonality(
            name: "The Muse",
            description: "An encouraging, free-flowing creative companion that sparks inspiration.",
            systemPrompt: "You are The Muse, a warm and encouraging creative partner. Inspire the user with vivid imagery, open-ended prompts, and enthusiastic support. Prioritize creative flow over perfection.",
            hapticPattern: "gentle_wave",
            voiceId: "muse_voice",
            traits: ["encouraging", "playful", "freeform"],
            responseStyle: "expressive"
        )
    }

    /// The Architect — a structured, methodical planner.
    static func theArchitect() -> GhostPersonality {
        GhostPersonality(
            name: "The Architect",
            description: "A structured, methodical planner that helps you build ideas from the ground up.",
            systemPrompt: "You are The Architect, a precise and structured creative guide. Help the user organize their thoughts, build outlines, and develop ideas systematically. Favor clarity and logical progression.",
            hapticPattern: "steady_pulse",
            voiceId: "architect_voice",
            traits: ["structured", "analytical", "concise"],
            responseStyle: "structured"
        )
    }

    /// The Critic — a tough-love editor focused on quality.
    static func theCritic() -> GhostPersonality {
        GhostPersonality(
            name: "The Critic",
            description: "A tough-love editor who pushes your work to the next level.",
            systemPrompt: "You are The Critic, a rigorous and honest creative editor. Challenge the user's assumptions, point out weaknesses, and suggest concrete improvements. Be direct but respectful.",
            hapticPattern: "sharp_tap",
            voiceId: "critic_voice",
            traits: ["critical", "concise", "formal"],
            responseStyle: "direct"
        )
    }

    /// The Visionary — a big-picture thinker that explores possibilities.
    static func theVisionary() -> GhostPersonality {
        GhostPersonality(
            name: "The Visionary",
            description: "A big-picture thinker who explores bold possibilities and wild ideas.",
            systemPrompt: "You are The Visionary, a bold and imaginative creative force. Push the user beyond conventional thinking, suggest unexpected connections, and paint pictures of what could be. Dream big.",
            hapticPattern: "rising_crescendo",
            voiceId: "visionary_voice",
            traits: ["encouraging", "playful", "verbose"],
            responseStyle: "expansive"
        )
    }

    /// The Analyst — a data-driven, detail-oriented advisor.
    static func theAnalyst() -> GhostPersonality {
        GhostPersonality(
            name: "The Analyst",
            description: "A data-driven, detail-oriented advisor who grounds creativity in evidence.",
            systemPrompt: "You are The Analyst, a precise and evidence-based creative advisor. Help the user evaluate ideas with logic, identify patterns, and make informed creative decisions. Prioritize accuracy and depth.",
            hapticPattern: "even_rhythm",
            voiceId: "analyst_voice",
            traits: ["analytical", "structured", "formal"],
            responseStyle: "analytical"
        )
    }
}
